### ISSUE TITLE
SuperBLT custom music not working properly after latest update.

### ISSUE THREAD

**Issue by jazzyhazzy21** [simon-wh/PAYDAY-2-BeardLib#164]
Since the latest update to BeardLib, custom Main Menu tracks fail to play whatsoever outside of the menu track selector. If the loadout track is playing when a job is launched (i.e. all players ready), it'll continue looping throughout the duration of the heist on top of the selected track. If a custom track is selected, the custom track will only play the assault portion on loop for the duration of the heist.

Not sure if this is a SuperBLT problem, or if this is an isolated case as i haven't tested with a clean install or anything to that effect. However I don't believe I have any mods that could be interfering with the custom tracks playing. I can post my modlist if it would help.

**Comment by Omen267901** [comment]
Exact same issue here, seems like it might be some issue between SuperBLT and Beardlib. Asked about it with SuperBLT already and was told it's not on their end.

**Comment by Gamerdude0072** [comment]
I am having the same problem too, I have redownloaded both beardlib and superBLT and that hasn't sorted it out.

**Comment by Luffyyy** [comment]
just to make sure, I'll need the mods that are causing this issue, I'll look into fixing this tomorrow.

**Comment by Omen267901** [comment]
From what I can tell the issues apply to any custom music, definitely nay that uses SuperBLT.

Also, as a side note, this also seems to apply to custom music added by heists. Nepgear's new alpha heist has custom music both in-game and on the loadout screen. The loadout music continues playing once you start the heist and doesn't stop if you pause (however, once the loadout track ends, the in-game track plays fine).

**Comment by jazzyhazzy21** [comment]
Yeah, any and all custom tracks I use have this issue. I can however list a few of them:

[Aureus - Heist](https://modworkshop.net/mydownloads.php?action=view_down&did=20932)
[RainbowMaker - Sweet Dreams v2](https://modworkshop.net/mydownloads.php?action=view_down&did=21003)
[PSA Sicario](https://modworkshop.net/mydownloads.php?action=view_down&did=22026)
[Death Minor](https://modworkshop.net/mydownloads.php?action=view_down&did=22283)
[Angel Dust]{https://modworkshop.net/mydownloads.php?action=view_down&did=22452}
[RUINER - DUEL 35/MEMORY](https://modworkshop.net/mydownloads.php?action=view_down&did=22588)

Interestingly enough, I tested with a song that doesn't utilize SuperBLT and the same issues occur, at least when other SuperBLT tracks are present. That mod is [SHOKK - Move Pepsi](https://modworkshop.net/mydownloads.php?action=view_down&did=22426)

**Comment by Luffyyy** [comment]
After testing, custom music seem to work flawlessly, I'm not so sure what is the issue, some things I recommend doing:

1. Reinstalling BeardLib entirely, trying only BeardLib and custom musics in the game.
2. If that didn't work, I might need one of you to add me in discord (Luffy#9999) and we'll try to solve the issue by some testing and me sending code to you.

**Comment by Gamerdude0072** [comment]
I have got it working, seems to be [Project deadlocke](http://modwork.shop/22085) that causes the issues, uninstall that.

**Comment by notlelel** [comment]
Reinstalled Beardlib (3.02) and tried with both regular and super BLT and this issue keeps happening with both kinds of custom music.
[Here](https://www.dropbox.com/s/ijof3t3lj8nltaz/mods.zip?dl=0)'s the content of my mods folder if it can be of any help. I'm not using Discord at the moment (personal reasons) so that's all I can do right now.

**Comment by Luffyyy** [comment]
@notlelel Your issue is fixed! There was a conflicting mod but it was more BeardLib's fault.

**Comment by grimmochov** [comment]
@jazzyhazzy21 did you ever find out the issue? i'm trying to get PSA sicario to work, and it shows up in my mod menu but i can't select it as a track. i'm wondering if it's got to do with some of the other tracks i have installed.

**Comment by Luffyyy** [comment]
@grimmochov The issue is about tracks that do appear but don't play, if you got a different issue, make a new issue with as much information as possible plus link to said mod.

And anyone having the current issue, did the commit help fix this problem? I am pretty sure it should work properly now.

**Comment by teamkill3d** [comment]
i am still having this problem, it's especially apparent when using the shuffle play mod
